heroTitle: "Bem-vindos a Castelo de Paiva"
heroSubtitle: "Descubra a beleza natural, a rica história e as tradições do nosso município. Fique a par de todas as novidades, eventos e serviços disponíveis."
heroImage: "/images/castelo-paiva-hero.jpg"
featuredSections:
  - title: "Notícias"
    description: "Mantenha-se informado sobre as últimas novidades do município"
    icon: "newspaper"
    link: "/noticias"
  - title: "Eventos"
    description: "Descubra os próximos eventos culturais e desportivos"
    icon: "calendar"
    link: "/eventos"
  - title: "Serviços Online"
    description: "Aceda aos serviços municipais de forma rápida e simples"
    icon: "computer"
    link: "/servicos"
  - title: "Turismo"
    description: "Explore as belezas naturais e património de Castelo de Paiva"
    icon: "map"
    link: "/turismo"
newsCount: 6