mainMenu:
  - title: "Início"
    url: "/"
  - title: "Notícias"
    url: "/noticias"
  - title: "Eventos"
    url: "/eventos"
  - title: "Município"
    url: "/municipio"
    submenu:
      - title: "História"
        url: "/municipio/historia"
      - title: "Geografia"
        url: "/municipio/geografia"
      - title: "Símbolos"
        url: "/municipio/simbolos"
  - title: "Serviços"
    url: "/servicos"
    submenu:
      - title: "Atendimento Online"
        url: "/servicos/online"
      - title: "Contactos"
        url: "/servicos/contactos"
      - title: "Horários"
        url: "/servicos/horarios"
  - title: "Turismo"
    url: "/turismo"
    submenu:
      - title: "Pontos de Interesse"
        url: "/turismo/pontos-interesse"
      - title: "Alojamento"
        url: "/turismo/alojamento"
      - title: "Restauração"
        url: "/turismo/restauracao"
  - title: "Contactos"
    url: "/contactos"