backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "content/noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - label: "Título"
        name: "title"
        widget: "string"
        required: true
      - label: "Data"
        name: "date"
        widget: "datetime"
        default: "{{now}}"
        required: true
      - label: "Imagem"
        name: "image"
        widget: "image"
        required: false
      - label: "Resumo"
        name: "summary"
        widget: "text"
        required: true
      - label: "Conteúdo"
        name: "body"
        widget: "markdown"
        required: true
      - label: "Categoria"
        name: "category"
        widget: "select"
        required: true
        options: 
          - "Notícias"
          - "Eventos"
          - "Turismo"
          - "Cultura"
        default: "Notícias"
