backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "noticias"
    label: "Notícias"
    folder: "content/noticias"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data de Publicação", name: "date", widget: "datetime" }
      - { label: "Imagem Destacada", name: "image", widget: "image", required: false }
      - { label: "Resumo", name: "summary", widget: "text" }
      - { label: "Categoria", name: "category", widget: "select", options: ["noticias", "eventos", "historia", "turismo"] }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
      - { label: "Publicado", name: "published", widget: "boolean", default: true }

  - name: "pages"
    label: "Páginas"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }

  - name: "config"
    label: "Configurações"
    files:
      - label: "Informações do Site"
        name: "site_info"
        file: "content/config/site.yml"
        fields:
          - { label: "Nome do Site", name: "site_name", widget: "string" }
          - { label: "Descrição", name: "description", widget: "text" }
          - { label: "URL", name: "url", widget: "string" }
          - { label: "Email de Contato", name: "contact_email", widget: "string" }
          - { label: "Telefone", name: "phone", widget: "string" }
          - { label: "Endereço", name: "address", widget: "text" }
